version: '3.7'

services:
  db:
    container_name: 'postgres'
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  app:
    container_name: 'app'
    build: .
    env_file:
      - .env
    ports:
      - '3333:3000'
volumes:
  db:
    driver: local
